### ISSUE TITLE
Feature request: switch to enable no-rollback for troubleshooting

### ISSUE THREAD

**Issue by jxuamazon** [aws-samples/pcluster-manager#101]
When creating a pcluster, if post_install_script fails,  headnode creation will cause the pcluster stack to rollback. Need to be able to enable no-rollback to keep the headnode for troubleshooting.

**Comment by charlesg3** [comment]
@jxuamazon  -- thanks for the feature request. Support for disabling rollback on cluster creation has been added in PR #112 .
