### ISSUE TITLE
New hosted zone every time a cluster is created ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#113]
I am learning PCM and creating/destroying cluster frequently.

I noticed that I get charge something call HostedZone every time I create a cluster.

Is there a way to reuse ? It gets expensive for short live cluster jobs.

![image](https://user-images.githubusercontent.com/486172/162556109-3ea541f6-4925-4f82-bfb7-d1b767152952.png)

**Comment by sean-smith** [comment]
yes, you can set the following parameters in your config:

```yaml
Dns:
  DisableManagedDns: true
  HostedZoneId: hosted-zone-id
```

See https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#Scheduling-v3-SlurmSettings-Dns.properties for more details.

I wouldn't advise this though, I'd be more curious to know why you're creating/destroying clusters so often as opposed to stopping them and re-using?

**Comment by nyue** [comment]
Agreed, leave the DNS properties as per it's original design intention.

As to why I am creating/destroying so frequently : It is only during my initial learning phase, in production situation, I should already know all the ins-outs and create an optimised cluster fit for the work load. It is during this learning phase that I have to do many experimentation/iteration and hence so many create/destroy.

FYI, I am experimenting with the following combination to understand how a cluster performance are affected

- Static/dynamic nodes (On-demand vs spot)
- Placement group
- 3 variants of fileysystems (Luster, EBS,etc)
- Various network options (EFA)

Hence trying the above out and different combination leads me to lots of create/destroy

Now that I understand the design rationale, I am closing the ticket.

Thank you :-)
