### ISSUE TITLE
Fix the ability to specify volume size on compute instances

### ISSUE THREAD

**Issue by mhuguesaws** [aws-samples/pcluster-manager#116]
There is an option to change the root volume size of the head node but not on the compute instances.
This issue is to add the option to specify compute instance root volume size.

**Comment by charlesg3** [comment]
Hi @mhuguesaws  -- thanks for your interest and the feature request. This should be relatively easy to add and should be addressed in the next few days.

Cheers!

**Comment by charlesg3** [comment]
The following PR should add this support when merged and deployed.
https://github.com/aws-samples/pcluster-manager/pull/117
