### ISSUE TITLE
pcluster-manager : creation failure ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#119]
I was about to demo the setup to some folks and encountered this failure so I had to cancel the demo

I noticed the new UI does not have the VPC drop down

![image](https://user-images.githubusercontent.com/486172/163252316-d054a236-2981-4331-ba5a-7d3cabb38df6.png)

**Comment by sean-smith** [comment]
Can you share your config? I just spun up pcluster manager in ca-central-1 to check

**Comment by nyue** [comment]
I deleted the stack a few hours ago.

I will try again now and we can compare notes.

**Comment by nyue** [comment]
Still failing for me, how to retrieve the config you need ?

**Comment by charlesg3** [comment]
Hi @nyue  -- I just tried creating a new Pcluster Manager in the `ca-central-1` region without issue. We haven't changed anything with the `ParallelClusterApi` resource, perhaps it was a transient issue or an issue with the VPC setup. Have you had success in this region before?

**Comment by nyue** [comment]
Yes, I have been using this region for over a week

There was a previous ticket I raise about creation failure which was addressed about 2 weeks ago and since than, I was able to create pcluster-manager

I have tried twice in the last 24 hours, both failed.

Cheers

**Comment by nyue** [comment]
For my situation, I have a work around for now.

The following UI which says the information is **optional**, in my case, I need to provide explicit (**default**) values, it is unable to pick up my VPC and Subnet information to build the ECRImage part

![image](https://user-images.githubusercontent.com/486172/163519594-8cfaedc8-f667-4e71-be2f-affcedae7113.png)

**Comment by sean-smith** [comment]
These are required if you don't have a default VPC or that VPC doesn't have internet connectivity. We previously had these as AWS intrinsic parameter types, i.e. it would autofill based on vpc's in your account, however we had to change this because it didn't allow making them optional, which imho is the default case.

**Comment by robertdeheer** [comment]
I'm seeing this issue even when the vpc_id and subnet are set.

**Comment by jpellman** [comment]
@robertdeheer - Not sure if this is still a problem for you, but I also encountered this issue when setting `vpc_id` and `subnet` and discovered that there are other conditions that need to be fulfilled for the CloudFormation template to properly deploy.  Namely, the documentation [here](https://aws.amazon.com/premiumsupport/knowledge-center/image-builder-verification-ssm-agent/) indicates that IPv4 address auto-assignment must be enabled if you're using a public subnet and that private subnets need for NAT to be configured.  Network ACLs and security groups can also be problematic apparently.
