### ISSUE TITLE
DCV settings fields editable?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#123]
The web UI provides 2 fields with pre-filled values (they are not greyed out)

Are the values editable ?

Not sure if it is a bug or this requires some other settings enabled/disable for the fields to be editable.

![image](https://user-images.githubusercontent.com/486172/164106726-5eec3ad2-a015-4d78-8bca-6c92eb4b0830.png)

**Comment by charlesg3** [comment]
Thanks for the report -- This should be fixed when this PR is deployed:

https://github.com/aws-samples/pcluster-manager/pull/126
