### ISSUE TITLE
Create User : bad request ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#124]
On the user tab/page when I click on Create User, I get a flyby red banner mentioning a bad request

Is this a bug or is there some other setup I need to perform before I am allow to create user ?

Cheers

**Comment by sean-smith** [comment]
No - create user should be available. Are you using MFA?

**Comment by nyue** [comment]
I am not using MFA.

**Comment by Silver-Linda** [comment]
I am also having this issue with pcluster manger. I am running in ohio, using a version of pcluster manager from a few days ago. Not using MFA.

![createuser](https://user-images.githubusercontent.com/101914703/166072450-242f8bd4-377a-46dd-aa69-222c8cb94a04.png)

**Comment by sean-smith** [comment]
Ok this issue comes from not entering (or entering an invalid) user email. We're adding validation to catch this in https://github.com/aws-samples/pcluster-manager/pull/136 but until then you can get around this by entering a valid email and **then** clicking create.
