### ISSUE TITLE
Invalid cluster configuration: Cannot find official ParallelCluster AMI

### ISSUE THREAD

**Issue by danielthrasher** [aws-samples/pcluster-manager#129]
Ive deployed the cloudformation stack provided on the Readme into our account.  Whenever I login to the pcluster-manager url and try to deploy our first cluster, I get this error - 

Invalid cluster configuration: Cannot find official ParallelCluster AMI

Everything deployed related to parallelcluster was done via the cloudformation stack in the readme.

Any help would be greatly appreciated.

**Comment by danielthrasher** [comment]
oh and the region im deploying into is us-gov-west-1

**Comment by danielthrasher** [comment]
Ah official images does not include Centos7 and thats what im trying to use

**Comment by cpollard0** [comment]
@danielthrasher - The centos7 image is not available in GovCloud (https://docs.aws.amazon.com/parallelcluster/latest/ug/Image-v3.html). One workaround you may want to try is to export the pcluster centos7 AMI from us-west-1 to S3, copy to s3 across partition, and reimport as a fresh AMI. @bollig has a gist for that here that could help you get started: https://gist.github.com/bollig/d14c30c23fc1aebe624af563180252ca

**Comment by danielthrasher** [comment]
Thanks!  Closing this issue.
