### ISSUE TITLE
What are the expected privileges of Guest user ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#137]
I have created a Guest user but it does now show much even though I have a cluster created and running.

![PCM_Guest](https://user-images.githubusercontent.com/486172/166112639-c2a9a49c-511e-499d-b630-a41105b1ab8d.png)

**Comment by sean-smith** [comment]
This is by design, `guest` is basically no permissions, `user` is read only & admin is everything. I think you want `user` in this use case.

**Comment by nyue** [comment]
What are the use case for `guest` ?

**Comment by sean-smith** [comment]
Anonymous user sign-in. So say someone comes along and clicks "Sign-in" this is what they see.

**Comment by charlesg3** [comment]
Guest is the role that anyone has until they have been upgraded to a user by an administrator. This allows people to be able to sign up using whatever email they want and the administrator to bestow access to them

**Comment by nyue** [comment]
Righto :-) @charlesg3
