### ISSUE TITLE
Stop Compute Fleet Spinning

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/pcluster-manager#150]
Stop Compute Fleet (from the Edit dialogue) never stops spinning even after the cluster stops.

**Comment by BarcoMasile** [comment]
Hi Sean, can you confirm this is still an issue?

**Comment by BarcoMasile** [comment]
I couldn't reproduce the bug.

**Comment by sean-smith** [comment]
Thanks yes I can still re-produce.
