### ISSUE TITLE
Cluster name in ParallelCluster Manager UI using underline

### ISSUE THREAD

**Issue by d3macalex** [aws-samples/pcluster-manager#210]
Not a big deal (I guess 😊) but, trying to create a cluster using ParallelCluster Manager UI, if you use a cluster name with an underline (I have tried first alxsouza_cluster) leads to an error in the Create stage (both Dry Run and Create buttons):
Bad Request: 'alxsouza_cluster' does not match '^[a-zA-Z][a-zA-Z0-9-]+$' - 'clusterName'
 
However, replacing the underline by a dash (alxsouza-cluster) works fine. Not sure you have seen this before, reason why I am reporting.
 
In sum, I guess this is an error we should notify the users at the SOURCE screen (or, at least, improve the error message in the last step).

**Comment by charlesg3** [comment]
Thank you for the report!

This should be fixed in #209  -- once that PR is merged and the next release goes out this should be fixed with much earlier validation.
