### ISSUE TITLE
Cannot create new cluster and cannot load the code editor for PCluster v3.1.4 and v3.2.0

### ISSUE THREAD

**Issue by xuanus** [aws-samples/pcluster-manager#238]
Deployed a pcluster manager with PCluster v3.1.4 or v3.2.0 (just use the default CF input)
When creating a new cluster (just use the default input), it will show "There was an error loading the code editor. Retry"
<img width="1033" alt="Screen Shot 2022-08-02 at 5 13 23 PM" src="https://user-images.githubusercontent.com/9119888/182497675-62ada5eb-18dc-4ce5-8a51-df82cd92977b.png">
 
 
 https://github.com/aws/aws-parallelcluster/tags

**Comment by mtfranchetto** [comment]
PCluster Manager version 3.2.0 has been released which fixes this issue. Let me know if it works for you!

**Comment by sean-smith** [comment]
An FYI to this @xuanus if you're using ParallelCluster version prior to 3.2.0, I recommend you launch a new GUI stack and change the version in the CFN parameters to the same version as the cluster, this will allow you to make updated to the previous cluster and resolves the Ace Code editor bug. See https://pcluster.cloud/01-getting-started/02-pcmanager-install.html for deployment options

**Comment by xuanus** [comment]
Works. Thank you!

**Comment by xuanus** [comment]
If select the failed deployment, it will show the error :

<img width="1308" alt="Screen Shot 2022-08-09 at 7 08 06 PM" src="https://user-images.githubusercontent.com/9119888/183794837-c91c8407-299e-4f1e-ae27-811f0303a38f.png">

**Comment by mendaomn** [comment]
Closing in favor of #271 

We are investigating this issue
