### ISSUE TITLE
Cluster in `CREATE_FAILED` state cannot be selected/deleted

### ISSUE THREAD

**Issue by stephenmsachs** [aws-samples/pcluster-manager#271]
When I try to click on a cluster in `CREATE_FAILED` state, I get the following error message. As I cannot select the cluster,I also cannot delete it. Deleting the cfn stack through the cfn console works fine though.

```
"Error (test1): Unable to parse configuration file. Unable to load configuration from bucket 'parallelcluster-59b87411cc92e432-v1-do-not-delete/parallelcluster/3.2.0/clusters/test1-6eq6qmec6ui5aqkn'. The specified version does not exist."
```

**Comment by mendaomn** [comment]
We'll look into this, thank you
