### ISSUE TITLE
parallelCluster Manager 3.2.0 failed on PERSISTENT_2 Lustre creation

### ISSUE THREAD

**Issue by cyberchip-wang** [aws-samples/pcluster-manager#274]
parallelCluster Manager 3.2.0 created with https://www.hpcworkshops.com/03-deploy-pcm/01-deploy-pcm.html does not propagate PerUnitStorageThroughput to the final Cluster Configuration. This caused the "Dry Run" failed. The workaround is adding a line manually to the Cluster Configuration template file: PerUnitStorageThroughput: 125

Screenshots:
![Storage Properties](https://user-images.githubusercontent.com/111794603/186234805-ec70050a-c08e-48a2-9dcd-a9093c83464a.png)
![Dry run error](https://user-images.githubusercontent.com/111794603/186234939-5550bc7e-78b7-4f85-b078-698ff5b285a3.png)

URL for AWS ParallelCluster Manager:
https://k0fymmi0ei.execute-api.us-east-2.amazonaws.com/home

The Lustre section in the Cluster Configuration:
SharedStorage:

Name: FsxLustre0
StorageType: FsxLustre
MountDir: /shared
FsxLustreSettings:
StorageCapacity: 1200
DeploymentType: PERSISTENT_2
DataCompressionType: LZ4
Dry Run error:

Invalid cluster configuration.
ValidationErrors:
FsxPersistentOptionsValidator: Per unit storage throughput must be specified when deployment type is PERSISTENT_2.

The issue can be reproduced by following the instructions from hpcworkshops:

Deploy the Pcluster Manager stack:
https://www.hpcworkshops.com/03-deploy-pcm/01-deploy-pcm.html
Create HPC Cluster:
https://www.hpcworkshops.com/06-fsx-for-lustre/01-create-cluster.html
Create FSx Lustre:
https://www.hpcworkshops.com/06-fsx-for-lustre/02-create-cluster-fsx.html

**Comment by sean-smith** [comment]
Thanks for pointing out this issue, we'll fix it asap. Until then you can add a line to the very bottom indented to the same level as DataCompressionType:

```bash
PerUnitStorageThroughput = 125
```
