### ISSUE TITLE
FSx Netap Ontap not displaying filesystems

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/pcluster-manager#276]
The drop down under the FSx Netapp Ontap filesystem section doesn't display the list of filesystems running in the region:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/5545980/186287510-5e347530-ada1-4405-b6bb-299d7a8ed32b.png">

**Comment by eantonin** [comment]
Thanks Sean, tracking it, we'll fix asap

**Comment by mtfranchetto** [comment]
@sean-smith can you add more details about the environment? Region used, PC version, state of the NetApp filesystem (they are filtered based on their state) and so on.

**Comment by sean-smith** [comment]
Sure, this is using `3.2.0` and I have the filesystems in region and I've tried both Multi-Az and Single-Az with the filesystem residing in the same AZ. Filesystem is running.

**Comment by mtfranchetto** [comment]
We found the root cause and the fix will ship with https://github.com/aws-samples/pcluster-manager/pull/284.
Until a new version of PCM is released, you can create/update a stack with the `pcluster-manager.yaml` template from the `main` branch of the repository.
Thank you.
