### ISSUE TITLE
[Wizard] Static count increase in the wizard results in an implicit Dynamic count increase

### ISSUE THREAD

**Issue by eantonin** [aws-samples/pcluster-manager#310]
A video showing the behaviour:
https://user-images.githubusercontent.com/83351137/193596820-e970820b-c751-40de-bc8c-6c6220d58dff.mp4

Pcluster version: 3.2.0
Pcluster manager one click launched from the link in github at commit a657d0cae4006db08810cd4b6d2c2f16ce0355dd
Region us-east-1

**Comment by mtfranchetto** [comment]
While this might not be the best user experience, it's actually the expected result.
You have 2 nodes always there (min 2) and 4 that can be spin up dynamically (hence max 6).
Closing the issue.
