### ISSUE TITLE
`PerUnitStorageThroughput` not added by default

### ISSUE THREAD

**Issue by stephenmsachs** [aws-samples/pcluster-manager#353]
When FSx Lustre is selected as Storage, the dropdoown selection for "Per Unit Storage Throughput" is pre-selected at 125. However, if no further selection is made there is no `PerUnitStorageThroughput` entry added to the `FsxLustreSettings` entry in the cluster config. This leads to ValidationError:
```
FsxPersistentOptionsValidator: Per unit storage throughput must be specified when deployment type is PERSISTENT_2.
```

When selecting "125" from the dropdown the `PerUnitStorageThroughput` is present in the config.

**Comment by mtfranchetto** [comment]
Hello Stephen,
this has been already asked in https://github.com/aws-samples/pcluster-manager/issues/274 and fixed. 
The fix will be released publicly this week. Stay tuned!
