### ISSUE TITLE
Creating new cluster using parallel cluster manager fails

### ISSUE THREAD

**Issue by joshvmaws** [aws-samples/pcluster-manager#361]
Upon creating a new cluster through pcluster manager, the cfn stack fails with "User does not have permission to create  cloudwatch log group with tags". I believe all users in ca-central-1 should have the same issue on new installations. I've tested with two different pcluster-manager 3.3.0 installations and I see the same behaviour.

Recently, there has been a change in behaviour in aws on creating cloudwatch log groups with tags. It now needs explicit "logs:TagLogGroup" permissions  in the IAM role "xxx-ParallelC-ParallelClusterUserRole-xxx" for it to be able to create log groups with tags. I tested by manually adding an inline policy to this iam role and I could successfully create the cluster.

This role is created by the resource "ParallelClusterUserRole" in parallelcluster-api.yaml template.

**Comment by mendaomn** [comment]
Thank you, will look into this and get back to you

**Comment by mendaomn** [comment]
Opened an issue in the ParallelCluster project, you can follow the developments there as well

https://github.com/aws/aws-parallelcluster/issues/4529

**Comment by joshvmaws** [comment]
Thank you @mendaomn

**Comment by mendaomn** [comment]
The ParallelCluster team [posted a workaround](https://github.com/aws/aws-parallelcluster/issues/4529#issuecomment-1323875845) (similar to what you already did)

I'll keep this issue open until a fix is released

**Comment by mendaomn** [comment]
The issue has been fixed and release. You will need to re-install PCM (or just the PC stack) to receive the update
