### ISSUE TITLE
blank login screen

### ISSUE THREAD

**Issue by jhthpc** [aws-samples/pcluster-manager#5]
I successfully ran the pcluster-manager CloudFormation template but when logging into the created "UserPoolDomain", all I get is a blank screen. This happens both when I'm on the vpn and when I'm not.

**Comment by sean-smith** [comment]
hi @jhthpc - use the `PclusterManagerUrl` in main cfn stack, see:

https://github.com/aws-samples/pcluster-manager/blob/main/install/README.md

**Comment by jhthpc** [comment]
Nothing like following directions and using the right URL.

All good, thank you very much.

**Comment by sean-smith** [comment]
No worries - we need to make this more clear

**Comment by jhthpc** [comment]
Now that I've successfully logged in, when will the manager support pcluster 3.0.3?

**Comment by sean-smith** [comment]
Updated to `3.0.3`!

You'll need to launch a new version of pcluster manager which will only be able to perform operations on `3.0.3` clusters, so keep that in mind. My suggestion would be to launch the new version in parallel to the older version, get a new cluster setup and make sure you have everything ported over before killing the old one.

**Comment by charlesg3** [comment]
@jhthpc -- thanks for your interest in Pcluster Manager. We're closing this issue as `3.0.3` is released. Please feel free to open a further issue if you run into anything else.

Cheers!

**Comment by jhthpc** [comment]
All good, thanks!

From: Charlie ***@***.***>
Reply-To: aws-samples/pcluster-manager ***@***.***>
Date: Tuesday, February 1, 2022 at 4:46 PM
To: aws-samples/pcluster-manager ***@***.***>
Cc: "THOMPSON, JOHN H. (GSFC-606.0)[ADNET SYSTEMS INC]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [aws-samples/pcluster-manager] blank login screen (Issue #5)


@jhthpc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhthpc&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7C9198a71668a647dd7caf08d9e5cc3fd1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637793487669315447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=veYauDeGuJ1FpZW2UHqW1E0vc23bm1F8ssM6xMUvj2E%3D&reserved=0> -- thanks for your interest in Pcluster Manager. We're closing this issue as 3.0.3 is released. Please feel free to open a further issue if you run into anything else.

Cheers!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faws-samples%2Fpcluster-manager%2Fissues%2F5%23issuecomment-1027317741&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7C9198a71668a647dd7caf08d9e5cc3fd1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637793487669315447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tLldOJcwG4xw%2B6Dka7eJ%2FKLPuKRHDyY%2Fcf4nCd%2BwWgI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXRPUV3UMPWIDQFYKRWQJ6TUZBIBVANCNFSM5NGUDNAA&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7C9198a71668a647dd7caf08d9e5cc3fd1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637793487669315447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zi0T5Ml9sSgBLh6rHjy4vAV5W%2BA5%2B9TrBGYj%2BH7GYzs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7C9198a71668a647dd7caf08d9e5cc3fd1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637793487669315447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cr%2FzXNIWCkm4QD1Og3r%2BBkRDiqdNAQHfDrnPKm%2BSqgw%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7C9198a71668a647dd7caf08d9e5cc3fd1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637793487669315447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0yOC2dptwZ2JGAEYS2%2FyH3yazsyrLUJ2nC4JjJ0VC9w%3D&reserved=0>.
