### ISSUE TITLE
Pcluster Manager not working on ap-south-1 region

### ISSUE THREAD

**Issue by dvpr-23** [aws-samples/pcluster-manager#549]
Dear BarcoMasile and Marco Basile,

I hope this finds you well. I am writing to bring your attention to an issue that I have encountered with the PCLuster Manager in the ap-south-1 region.

I have noticed that the shell and nice DCV icons are not visible when using the PCLuster Manager in the ap-south-1 region, while it is working perfectly fine in the N Virginia region. I understand the importance of having a smooth and seamless experience when using the PCLuster Manager and I am writing to request your assistance in resolving this issue.

I would greatly appreciate your prompt attention to this matter as it is affecting my ability to use the PCLuster Manager effectively in the ap-south-1 region. If you could provide any information on the status of this issue or a timeline for its resolution, I would be most grateful.

Thank you in advance for your time and assistance. I look forward to hearing back from you soon.

Best regards,

**Comment by mtfranchetto** [comment]
Hello @dvpr-23, this issue has been fixed but not released. We'll release it soon!

**Comment by dvpr-23** [comment]
Thank you @mtfranchetto . May i know the ETA on that.

Im really looking forward too it and very excited about that.

**Comment by mtfranchetto** [comment]
Hi @dvpr-23, unfortunately we do not provide ETA about future releases by policy, therefore I cannot provide you with an exact date for the time being. What I can tell you is that we are actively working on this and we plan to have it ready in a few weeks. I will provide an update on this ticket as soon as we will release the new version.

**Comment by dvpr-23** [comment]
Thank you @mtfranchetto 
but weeks seem to be bit long.
hoping and eagerly waiting for the release
Thank you though. Please update once the release happens
many of us in india are rooting for you

**Comment by mtfranchetto** [comment]
Hello @dvpr-23, you asked and we've released a new version of ParallelClusterManager, which has been renamed to ParallelCluster UI. Please head to the new repository to install the latest version https://github.com/aws/aws-parallelcluster-ui
