### ISSUE TITLE
ca-central-1 setup failed

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#68]
First time user, launching from Canada but encountered failure. Docker/EC2 image id hard coded for us-east-1 ?

```
./scripts/update.sh --region ca-central-1
Logging in to docker...
Login Succeeded
latest: Pulling from n0x0o5k1/pcluster-manager-awslambda
69e3a639bf87: Pull complete 
e5ad02396619: Pull complete 
8cce4e515b2a: Pull complete 
03ac043af787: Pull complete 
65e284713a7d: Pull complete 
eaacfb3c821c: Pull complete 
e8c62d590dcd: Pull complete 
3060f5d03faa: Pull complete 
27ef4d8fb12f: Pull complete 
9cef9f9d3a96: Pull complete 
8498e5ec098a: Pull complete 
88b8884bf765: Pull complete 
Digest: sha256:770178a924c2d260e98926e8d7292b569a34f53757d626b9648286c09cb986a1
Status: Downloaded newer image for public.ecr.aws/n0x0o5k1/pcluster-manager-awslambda:latest
public.ecr.aws/n0x0o5k1/pcluster-manager-awslambda:latest
Error parsing reference: "083230063072.dkr.ecr.ca-central-1.amazonaws.com/None:latest" is not a valid repository/tag: invalid reference format: repository name must be lowercase
```

**Comment by sean-smith** [comment]
@nyue My guess is you're running the update script without having first deployed the stack. Take a look at **More Regions (click to expand)** in the [README](https://github.com/aws-samples/pcluster-manager#quickstart-15-mins-) and click on the `ca-central-1` launch stack button:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/5545980/159353939-9df7918c-0a69-4e7a-b00d-2112f0986362.png">

**Comment by nyue** [comment]
I tried clicking on ca-central-1, it started creating the stack. After monitoring it (IN_PROGRESS) for about 30 minutes, I get a ROLLBACK_COMPLETE

It's like it has issue creating the stack

![pcluster-manager-rollback-compelete](https://user-images.githubusercontent.com/486172/159380538-0f240726-ae52-4999-bf3c-564c076182dc.png)

**Comment by sean-smith** [comment]
@nyue Can you check the stack events and find the event that failed? You might need filter by `FAILED` to get the correct stack.

**Comment by nyue** [comment]
I found the failure, it mentioned ECR

```
Embedded stack arn:aws:cloudformation:ca-central-1:083230063072:stack/pcluster-manager-ParallelClusterApi-HAUEC9DAO8LE/099a6170-a96b-11ec-9e63-024e96f96c22 was not successfully created: The following resource(s) failed to create: [EcrImage].
```
![pcluster_ecr_failed](https://user-images.githubusercontent.com/486172/159381040-a31d2fd3-e143-41a9-a6eb-60b7268007eb.png)

**Comment by cpollard0** [comment]
@nyue - Can you please share the error with the embedded stack? It should have information specific to the ECR failure.

**Comment by nyue** [comment]
I am not sure how to get to an embedded stack? Is that the same as a nested stack ?

I am using this ID to match `099a6170-a96b-11ec-9e63-024e96f96c22`

![image](https://user-images.githubusercontent.com/486172/160253343-0ddfea99-5617-4211-8b93-a699a9ce4135.png)

**Comment by cpollard0** [comment]
You've got the right stack! 

Yes, embedded stacks are synonymous with nested stacks.

Once CloudFormation finds a failure it will delete all the resources that it has created up to that point, so seeing all the resources as DELETE_COMPLETE is expected. 

Can please click on the Events tab of the stack and share information regarding the first failures you see?

FWIW I just deployed to ca-central-1 by clicking on the link @sean-smith sent and PCluster manager successfully installed.

**Comment by nyue** [comment]
Here are the events

![image](https://user-images.githubusercontent.com/486172/160253677-b46ac5a1-d8cc-4861-889b-0122b192eb47.png)

**Comment by cpollard0** [comment]
@nyue - Can you please scroll down the list of events and grab a screenshot the point at which you see the first error? The delete events happened subsequent to the error.

**Comment by nyue** [comment]
Here is the part where the creation failure message is visible. It mentioned SSM Agent

![image](https://user-images.githubusercontent.com/486172/160254195-04942250-329d-43dd-962c-809e1abc33e9.png)

**Comment by cpollard0** [comment]
Thanks for the detail! I think Image Builder uses the default VPC to build an image. What does that VPC look like in your environment? If there are private subnets do all their route tables have a NAT GW entry? Any NACLs in place? Any VPC or gateway endpoints with policies in place?

**Comment by nyue** [comment]
I am not an AWS power user, I never touch the networking stuff so I am struggling to comprehend the details and be able to find answers to the questions (even though I vaguely understand the questions and they look important).

I have been setting up MPI clusters via terraform and was hoping to do so via parallelcluster v3 seeing the configuration has move to YAML.

I am looking to pcluster-manager to make it simple for users like me to launch an MPI cluster, run some MPI aware applications be they rendering, genomics, visualization and shut them down once the work is done.

I am happy to learn about the VPC/network working stuff but am unable to provide useful answers at this juncture.

Cheers

**Comment by sean-smith** [comment]
Thanks @nyue 

This is exactly the type of use case we're building PCM to solve. We want to make it easy to deploy and manage HPC clusters without having to be an expert in AWS networking (which I'm not).

Specifically for this issue, I think the root of the problem comes from https://github.com/aws-samples/pcluster-manager/pull/55 which will be merged in the next few weeks. 

Basically the default VPC (which you can find [here](https://ca-central-1.console.aws.amazon.com/vpc/home?region=ca-central-1)) needs to exist and have a route to the internet. Once https://github.com/aws-samples/pcluster-manager/pull/55 is merged you'll be able to specify another VPC/Subnet outside of the default one to launch in.

**Comment by sean-smith** [comment]
Closing since https://github.com/aws-samples/pcluster-manager/pull/55 was merged
