### ISSUE TITLE
Limit EC2 instance choices based on region and AZ

### ISSUE THREAD

**Issue by skjerven** [aws-samples/pcluster-manager#69]
Generally, not all instance types, particularly GPU instances, are available in each AZ. As such, when a user creates a queue, there is no check to confirm if a selected EC2 instance class is available in the selected subnet. 

Also, there is no check to see if instances are available at a region level. Example: create a cluster in us-east-1, but HPC6a is listed as an option.

**Comment by charlesg3** [comment]
https://github.com/aws-samples/pcluster-manager/pull/78

**Comment by charlesg3** [comment]
Resolved in latest deploy.
