### ISSUE TITLE
Number of IAM Policies

### ISSUE THREAD

**Issue by skjerven** [aws-samples/pcluster-manager#70]
For the Slurm accounting in the `post-install-scripts` branch, we need to attach an additional IAM policy (SecretsManagerReadWritePolicy) to the role used by PclusterManagerFunction (see documentation here: https://aws-samples.github.io/pcluster-manager/02-tutorials/02-slurm-accounting.html)

That role has 10 policies already attached, which is the default max. This can be increased, but suggest trying to consolidate some of the policies.

Alternatively, the documentation should be updated to reflect the required limit increase.

**Comment by charlesg3** [comment]
Policies consolidated in this PR so there is 1 slot available for an additional policy. Further consolidation can be added down the road as well:

https://github.com/aws-samples/pcluster-manager/pull/84

**Comment by sean-smith** [comment]
Fixed in https://github.com/aws-samples/pcluster-manager/pull/121
