### ISSUE TITLE
SecretsManger IAM Policy

### ISSUE THREAD

**Issue by skjerven** [aws-samples/pcluster-manager#71]
For Slurm accounting, an AWS managed policy, `SecretsMangerReadWrite` is attached to allow for the injection of the Slurm database password into the Slurm configuration.

Suggest we create policy that is more restrictive...it only needs to be read-only...and attach that as part of the accounting mult-script runner option.

**Comment by sean-smith** [comment]
Hmm so I did a quick search of the IAM managed policies and couldn't find a Secrets Manager ReadOnly **managed** policy. We could create one, it's been documented [here](https://docs.aws.amazon.com/mediaconnect/latest/ug/iam-policy-examples-asm-secrets.html#iam-policy-examples-asm-secrets-in-a-region) and looks like:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": "arn:aws:secretsmanager:us-west-2:111122223333:secret:*"
        },
        {
            "Effect": "Allow",
            "Action": "secretsmanager:ListSecrets",
            "Resource": "*"
        }
    ]
}
```

However this creates a lot of additional complexity. I suggest we include this policy creation in the Slurm Account stack then attach it via `AdditionalIAMPolicies` in pcluster. This has the advantage of specificity, we can specify only the DB secret and no more.

**Comment by cpollard0** [comment]
If you need read access to a single secret you should be able to use:  

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [ 
                "secretsmanager:GetSecretValue"
            ],
            "Resource": "arn:aws:secretsmanager:us-west-2:111122223333:secret:SECRETNAME"
        }
    ]
}

**Comment by charlesg3** [comment]
https://github.com/aws-samples/pcluster-manager/commit/8584d92ebf555bffea3409c5b1edf757cbcc3f3f

https://github.com/aws-samples/pcluster-manager/commit/195a2a7ae5e49452fb1f40139bc54bad0a2b8c1c
