### ISSUE TITLE
pcluster manager - shutdown procedure ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#76]
Hi,

  I have successfully launch pcluster manager.

  As there are many nested resources, is there a single point of entry where we can do a clean shutdown to ensure that all the resources spurn up for a given pcluster is all gone and does not continue to charge to our account ?

Cheers

**Comment by sean-smith** [comment]
Hi @nyue - 

Yes the `pcluster-manager` main stack will delete everything.

**Comment by nyue** [comment]
If I have created compute cluster via pcluster manager, would the deletion of the main stack also delete all the created cluster resources ?

**Comment by sean-smith** [comment]
No it won't. you'll need to delete those stacks as well. This is by design
