### ISSUE TITLE
Sanity checking on root volume size

### ISSUE THREAD

**Issue by OliverPerks** [aws-samples/pcluster-manager#85]
Manager let me enter an arbitrary value (e.g. 20 GB) then create fails.
```
  LocalStorage:
    RootVolume:
      Size: 20
```

```
Invalid cluster configuration.
Validation Errors:
ConfigSchemaValidator: [('HeadNode', {'LocalStorage': {'RootVolume': {'Size': ['Root volume size 20 is invalid. It must be at least 35.']}}})]
```

Would be preferable to have sanity checking on the input fields to prevent this.

**Comment by OliverPerks** [comment]
Well the 35 GB comes from the size definition of the AMI, right? So yes, >= 35GB.
Is it easy to query what the specific AMI volume size will be? 
If the base AMI size changed or using a custom AMI, it would be nice if this was adaptive. I appreciate that this sounds more like a feature request at this point.

**Comment by sean-smith** [comment]
So for default AMI's we don't know the AMI size before the cluster is created, that being said the minimum size is alwats 35GB.

I think your ask here is that we validate the size before you get to the `DryRun` portion so it's easier to correct.

**Comment by OliverPerks** [comment]
Sounds good to me. Happy with >=35.

**Comment by charlesg3** [comment]
@OliverPerks — thanks for the request, it should be easy to check for the appropriate volume size and have an error before moving on.

**Comment by charlesg3** [comment]
The following PR fixes this issue.

https://github.com/aws-samples/pcluster-manager/pull/109
