### ISSUE TITLE
Bad Request in email link

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#86]
Hi,

  I created a stack in the ca-central region yesterday

  I have tried connecting via the link sent via the email from AWS/Cloudformation

  I have still been unable to utilize the pcluster manager service

  I get the following HTTP error when connecting to the link

![image](https://user-images.githubusercontent.com/486172/161296101-4cec2061-8bf4-4b33-bd4a-227108c13fba.png)

Cheers

**Comment by nyue** [comment]
I have since deleted the stack as I don't want it to cost me while I cannot access it.

**Comment by sean-smith** [comment]
This will be fixed in PR #83

Sorry about that.

On Apr 1, 2022, at 8:41 AM, Nicholas Yue ***@***.***> wrote:

﻿

I have since deleted the stack as I don't want it to cost me while I cannot access it.

**Comment by sean-smith** [comment]
Fixed now!
