### ISSUE TITLE
mssh connection : how to specify ssh key?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#87]
I am trying out a connection via

![image](https://user-images.githubusercontent.com/486172/161327884-0f8ddd5a-1e9b-4fd6-b7cd-d1c69ada8fa1.png)

It requires my ssh key but there is no option to provide that via the mssh command line tool

Maybe I am going about it the wrong way.

**Comment by sean-smith** [comment]
@nyue The `mssh` command automatically synchronizes ssh keys for you. You'll aws creds setup locally and the EC2 Instance connect CLI installed `pip install ec2instanceconnectcli`. Then it just works!

If you'd prefer to use normal SSH just grab the head node ip from the instances tab and SSH like:

```bash
ssh -i ~/.ssh/id_rsa ec2-user@ip
```
