### ISSUE TITLE
cluster deletion failure : browser send protocol server does not understand

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#88]
After creating a test cluster, I am now not able to delete the cluster via the web UI

I am getting a fleeting message saying some browser protocol the server does not understand

Hope this can be resolved soon or a work around to shutdown the cluster completely and cleanly.

Cheers

**Comment by sean-smith** [comment]
was able to reproduce looking into it.

In the meantime you can delete the stack directly from the Cloudformation console.

**Comment by charlesg3** [comment]
Hi @nyue  -- thanks for the report and continued interest! I tracked down the issue and pushed a fix to the backend. When you get a chance can you re-deploy your stack and confirm if it's working on your end?

Cheers!

**Comment by nyue** [comment]
Hi @charlesg3 -- I am now able to delete my cluster from pcluster manager web ui.
