### ISSUE TITLE
DCV : Direct connection from my local machine ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#89]
I am able to utilise DCV via the DCV button on pcluster manager. It opens up DCV in the browser and I can interact graphically with it.

However, I was wondering if I am also able to connect via DCV to my head node on my local desktop NICE DCV application

I tried but I get the following error

![image](https://user-images.githubusercontent.com/486172/161332659-93d2d8c6-f801-4f36-8f35-82e9d8da4fe7.png)

**Comment by sean-smith** [comment]
Not currently - feel free to add to roadmap
