### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by Shattoww** [aws-samples/pcluster-manager#91]
![image](https://user-images.githubusercontent.com/12117979/161354411-164107d7-dd0a-46a1-baf8-560312460d75.png)

Seems like I'm missing some buttons here. I don't see shell, DCV, or anything else in my deployed manager. Any thoughts here?

**Comment by nyue** [comment]
@Shattoww I have noticed that on one occasion my panel has `DCV` missing, when I refresh the UI, it appears.

**Comment by charlesg3** [comment]
Hi @Shattoww — can you verify that DCV is enabled in your configuration? Did you try refreshing (sometimes this is rendered before the full configuration is available from the backend)
