### ISSUE TITLE
pcluster manager - cost

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#92]
Hi,

  If I only have a cluster manager running (no cluster created), what is the approximate costs (per hour or per day) ?

  Is there also available information breakdown for one-off (setup) and on-going (ec2/ecr) costs ?

Cheers

**Comment by sean-smith** [comment]
@nyue The cost to use pcluster manager is very low, in most cases it'll fall into the free tier and you won't pay anything. 

It's built on a completely serverless architecture, so there's nothing running unless you actively connect to the interface.

**Comment by nyue** [comment]
Got it.
