### ISSUE TITLE
Custom AMI Images - persistence ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#93]
Hi,

  If I go through the process of creating a custom AMI image with all the required tools and configuration done, I believe I should be able to create all subsequent cluster to use those custom AMI images.

  However, if I were to shutdown the pcluster manager stack, what will happen to those custom AMI images ? Will they be deleted ? Or will they appear in my next creation of a new pcluster manager stack ?

  If the pcluster manager build custom AMI images are not persisted, does it make sense to build custom images outside of pcluster manager ? How will pcluster manager know of their existence ?

Cheers

**Comment by sean-smith** [comment]
Hi @nyue,

All images (and clusters) are persisted even if you delete `pcluster-manager`. The manager stores no state, so images and clusters are preserved in your account via AMI section in EC2 or CloudFormation for clusters.

**Comment by nyue** [comment]
Got it. Thank you.
