### ISSUE TITLE
Custom Images - Building Wizard ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#95]
Are there plans to have some wizard or more elaborate UI to help with building custom AMI ?

Currently, the UI just ask for a YAML configuration.

I think a wizard will be helpful to also spread best practices in the YAML it generates.

Cheers

**Comment by sean-smith** [comment]
yes, I think for a start we could pre-fill a sample yaml template from: https://docs.aws.amazon.com/parallelcluster/latest/ug/Build-v3.html

**Comment by nyue** [comment]
Yes, a pre-fill sample that works out of the box building a usable Custom AMI is a great start.
