### ISSUE TITLE
Stopped cluster - head node still running ?

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#97]
Hi,

  When I stop a cluster, I noticed that the head node is still running while all the compute nodes are terminated.

  Is this by design ?

Cheers

**Comment by sean-smith** [comment]
Yes and you can stop the head node on the instances tab.

On Apr 2, 2022, at 5:06 PM, Nicholas Yue ***@***.***> wrote:

﻿

Hi,

When I stop a cluster, I noticed that the head node is still running while all the compute nodes are terminated.

Is this by design ?

Cheers

**Comment by sean-smith** [comment]
When the cluster is stopped the "Stop" button on the HeadNode will be available:

![image](https://user-images.githubusercontent.com/5545980/161590835-5a46f867-830e-4a2f-bb6c-cf47cde87c03.png)

**Comment by nyue** [comment]
Cool. Thanks for that.
